version: 2
jobs:
  build:
    docker:
      - image: cimg/openjdk:14.0-node

#    you can override the local-config.conf file with environment variables
#    environment:


    steps:
      - checkout

#        run the tests
      - run: chmod +x gradlew
      - run: ./gradlew clean build

      #        publish the test reports
      - run:
          name: Compress Artifacts
          command: tar -cvzf testReport.tar target
      - store_artifacts:
          path: testReport.tar
          destination: testReport